# Generated by Django 4.0.2 on 2023-10-01 01:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('user', 'date')},
        ),
    ]
