# Generated by Django 4.0.2 on 2022-02-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='external_cue',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='habit',
            name='internal_cue',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='habit',
            name='plan_of_action',
            field=models.TextField(max_length=200),
        ),
    ]
