# Generated by Django 4.0.2 on 2023-10-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_day_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='color_status',
            field=models.CharField(default='green', max_length=10),
        ),
    ]
