# Generated by Django 4.0.2 on 2023-10-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_day_color_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='color_status',
            field=models.CharField(max_length=10),
        ),
    ]
